# [PROJE YAPILANDIRMASI] 
# Veri seti Google Drive üzerinde 'Proje_Ham_Veriler' klasöründe saklanmaktadır.

path: /content/drive/MyDrive/Proje_Ham_Veriler  # Ana veri yolu
train: train/images   # Eğitim resimlerinin alt klasörü
val: valid/images     # Doğrulama resimlerinin alt klasörü

nc: 6
names:
  - patlican
  - muz
  - patates
  - havuc
  - salatalik
  - curuk_muz
