<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.25.0" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime.Managed" Version="1.25.0" />
    <PackageReference Include="OpenCvSharp4.Extensions" Version="4.13.0.20260330" />
    <PackageReference Include="OpenCvSharp4.Windows" Version="4.13.0.20260302" />
    <PackageReference Include="System.Speech" Version="10.0.7" />
    <PackageReference Include="YoloDotNet" Version="4.2.0" />
  </ItemGroup>

</Project>
